title: snack overflow
description: graze technology blog
url: https://tech.graze.com
twitter: snack_overflow

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - Makefile
  - README.md
  - templates

paginate: 10

plugins:
  - jekyll-avatar
  - jekyll-feed
